# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Short exposure
tagline:          'engineering blah blah'
description:      'engineering blah blah.'
url:              http://jaroszue.github.io
baseurl:          /

author:
  name:           'Emil Jaroszuk'
  url:            http://jaroszue.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
