# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Short exposure
tagline:          'engineering bla bla'
description:      'bla bla bla.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Emil Jaroszuk'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
